<h1> 00. PyTorch Fundamentals Exercises </h1>

<h2><b>1. Documentation reading </b> </h2>

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

The documentation on torch.Tensor.
The documentation on torch.cuda.

In [ ]:
import torch

<h2> 2. Create a random tensor with shape (7, 7). </h2>

In [ ]:
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.8602, 0.0112, 0.9192, 0.5726, 0.5572, 0.7392, 0.2763],
        [0.7506, 0.7426, 0.9958, 0.5213, 0.0484, 0.4747, 0.5653],
        [0.3938, 0.0699, 0.2018, 0.9089, 0.5309, 0.8387, 0.8047],
        [0.4663, 0.0817, 0.5603, 0.9848, 0.8614, 0.3307, 0.3276],
        [0.6226, 0.7743, 0.4891, 0.9436, 0.9290, 0.5744, 0.8451],
        [0.1576, 0.4336, 0.9015, 0.5216, 0.5608, 0.7946, 0.4579],
        [0.2292, 0.5597, 0.3819, 0.3775, 0.0336, 0.9545, 0.4221]])

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor). ##

In [ ]:
tensor_2 = torch.rand(1,7)

result = random_tensor @ tensor_2.T

## 4. Set the random seed to 0 and do 2 & 3 over again. ##

In [ ]:
torch.manual_seed(42)
random_tensor = torch.rand(7,7)

tensor_2 = torch.rand(1,7)

result = random_tensor @ tensor_2.T

print(result,random_tensor,tensor_2)


tensor([[1.3299],
        [1.8111],
        [1.3228],
        [0.9725],
        [1.8285],
        [1.4806],
        [2.0489]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]]) tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071]])


## 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [ ]:

torch.cuda.manual_seed(42)





## 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(1234)
tensor_1 = torch.rand((2,3))
tensor_2 = torch.rand((2,3))

tensor_1 = tensor_1.to(device)
tensor_2 = tensor_2.to(device)

print(tensor_1,tensor_2)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors). ##

In [ ]:
result = tensor_1 @ tensor_2.T
print(result,result.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


## 8. Find the maximum and minimum values of the output of 7. ##

In [ ]:
print(result.max(),result.min())

tensor(0.5617, device='cuda:0') tensor(0.3647, device='cuda:0')


## 9. Find the maximum and minimum index values of the output of 7. ##

In [ ]:
print(torch.argmax(result),torch.argmin(result))

tensor(3, device='cuda:0') tensor(0, device='cuda:0')


## 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape. ##

In [ ]:
torch.manual_seed(7)


tensor = torch.rand(1,1,1,10)

print(tensor,tensor.shape)
new_tensor = torch.squeeze(tensor,dim=0).squeeze(dim=0).squeeze(dim=0)

print(new_tensor,new_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
